import { z } from 'zod';
import { defineContract, fn, named } from '@/kit/contract';

export const StepFrame = named(
  'StepFrame',
  z.object({
    cells: z.array(z.union([z.number(), z.string()])).min(1).describe('Array contents at this step (numbers draw as bars)'),
    caption: z.string().optional().describe('What happens in this step'),
    hl: z.array(z.number().int()).optional().describe('Indexes being compared (teal)'),
    swap: z.array(z.number().int()).optional().describe('Indexes just swapped (orange)'),
    done: z.array(z.number().int()).optional().describe('Indexes in their final place (green)'),
    ptr: z.record(z.string(), z.string()).optional().describe('Pointer labels under cells, e.g. { "0": "i", "3": "j" }'),
    vars: z.record(z.string(), z.union([z.string(), z.number()])).optional().describe('Variables shown under the caption'),
  }),
);
export type StepFrameT = z.input<typeof StepFrame>;

export const stepper = defineContract({
  type: 'Stepper',
  category: 'visual',
  tone: 'teal',
  pill: 'Step through',
  purpose: 'Plays an algorithm frame by frame on an array (bars or boxes) with highlights, pointers, variables and a caption. Play/pause, step, scrub, speed.',
  whenToUse: 'Sorting and searching algorithms, two-pointer techniques, stack/queue operations, any process on a list. Generate frames with a function that runs the algorithm and records each step.',
  notes: ['Keys: ← → step, Space plays/pauses.'],
  schema: z.object({
    title: z.string().default(''),
    steps: z.union([z.array(StepFrame).min(1), fn<() => StepFrameT[]>('() => StepFrame[]')]).describe('Frames, or a function that generates them (preferred for algorithms)'),
    bars: z.boolean().default(true).describe('Draw numeric cells as bars; false = equal boxes'),
  }),
  snippet: {
    title: 'Binary search for 7',
    bars: false,
    steps: [
      { cells: [1, 3, 5, 7, 9], hl: [2], ptr: { '0': 'lo', '2': 'mid', '4': 'hi' }, caption: '5 < 7, so search the right half.' },
      { cells: [1, 3, 5, 7, 9], hl: [3], done: [3], ptr: { '3': 'mid' }, caption: 'Found 7 at index 3.' },
    ],
  },
  examples: {
    demo: {
      note: 'Bubble sort, generated by a function',
      props: {
        title: 'Bubble sort, one step at a time',
        steps: () => {
          const a = [5, 2, 8, 1, 9, 3];
          const n = a.length;
          const S: StepFrameT[] = [{ cells: [...a], caption: 'Bubble sort: compare neighbours and swap them if they’re out of order.', vars: { pass: 0 } }];
          const done: number[] = [];
          for (let p = 0; p < n - 1; p++) {
            let swapped = false;
            for (let j = 0; j < n - 1 - p; j++) {
              S.push({ cells: [...a], hl: [j, j + 1], done: [...done], ptr: { [j]: 'j', [j + 1]: 'j+1' }, caption: `Compare ${a[j]} and ${a[j + 1]}.`, vars: { pass: p + 1, j } });
              if (a[j] > a[j + 1]) {
                [a[j], a[j + 1]] = [a[j + 1], a[j]];
                swapped = true;
                S.push({ cells: [...a], swap: [j, j + 1], done: [...done], ptr: { [j]: 'j', [j + 1]: 'j+1' }, caption: `${a[j + 1]} > ${a[j]}, so swap them.`, vars: { pass: p + 1, j } });
              }
            }
            done.push(n - 1 - p);
            S.push({ cells: [...a], done: [...done], caption: `Pass ${p + 1} done: ${a[n - 1 - p]} has bubbled to its final place.`, vars: { pass: p + 1 } });
            if (!swapped) break;
          }
          S.push({ cells: [...a], done: [...Array(n).keys()], caption: 'Sorted. Worst case O(n²) comparisons.' });
          return S;
        },
      },
      wide: true,
    },
    boxes: {
      note: 'Static frames, bars: false',
      props: {
        title: 'Binary search for 7',
        bars: false,
        steps: [
          { cells: [1, 3, 5, 7, 9, 11, 13], ptr: { '0': 'lo', '3': 'mid', '6': 'hi' }, hl: [3], caption: 'mid = 3 → value 7. Found it on the first try!', vars: { lo: 0, hi: 6, mid: 3 } },
          { cells: [1, 3, 5, 7, 9, 11, 13], done: [3], caption: 'Binary search halves the range each step: O(log n).' },
        ],
      },
    },
  },
});
